### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by 4x10m** [Sadikk/BlueSheep#2]
Salut sadikk,
tu pourrais me contacter pour discuter de bluesheep ? axiiom.home@gmail.com

**Comment by Sadikk** [comment]
Discute en ici

**Comment by 4x10m** [comment]
salut vous, ça va ?

j’ai commencer a regarder un peu bluesheep mais j’ai un peu besoin d’aide.
je voudrais savoir ou tu t’étais arrêter et pourquoi ?
et aussi j’ai un problème sur l’encryption RSA des identifiants d’utilisateur, tu pourrais m’aider a fixer cela ?
y’a t’il une communauté a part cadrerais qui est encore intéressé par le bot socket ? 

merci

**Comment by Sadikk** [comment]
L'encryption RSA fait parti d'un nouvel antibot. Je te laisse rechercher ça sur le client ;)
