### ISSUE TITLE
Missing .DLLs

### ISSUE THREAD

**Issue by izackp** [Sadikk/BlueSheep#3]
These .DLLs are missing from the project:

DevComponents.DotNetBar2.dll
ICSharpCode.SharpZipLib.dll

I'm not sure if this was intentionally left out:
No.Ankama.dll

**Comment by MyHand** [comment]
hi

In fact, DevComponents.DotNetBar2 = DotNetBar2 (google it). Just download it and add the dll to the project. 

ICSharpCode.SharpZipLib.dll is already in the folder of the bot. Check %appdata%\BlueSheep.

**Comment by Sadikk** [comment]
Fixed. 

Thanks.
